---
title: "Spatial analyses of 2020-21 excess mortality in CH"
subtitle: "Analyses using AR"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales,  
       sf, tmap,
       INLA)

import::from("sjmisc", "frq")
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)
```

<!-- ----------------------------------------------------- -->

# Setup 

## Data

## Spatial 

```{r}
ar21 <- readRDS("data/BfS/ar21.Rds")
# argr21 <- readRDS("data/BfS/argr21.Rds")
# tg3o_ar <- readRDS("data/geo/tg3o_ar.Rds")
```

<!-- ----------------------------------------------------- -->

# Stratified modelling

```{r}
ar_strat_iid <- read_rds("results/ar_strat_iid.Rds")
```

## Model 

```{r}
model_strat <- ar_strat_iid$`80+ Male`
summary(model_strat)
model_strat$summary.hyperpar
```

## Month 

```{r}
model_strat_month <- model_strat$summary.random$month %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

model_strat_month %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()
```

## Year 

```{r}
model_strat_year <- model_strat$summary.random$id_year %>% 
  mutate(ID = ID + 2014, 
         `0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

model_strat_year %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()
```

## Observed vs predicted

```{r}
model_strat_fit <- bind_cols(
  data_strat,
  model_strat$summary.fitted.values
) %>% 
  mutate(split = ifelse(date <= as.Date("2019-12-01"), "Pre", "Pand"))

ggplot(model_strat_fit) + 
  geom_point(aes(x = `0.5quant`, y = observed), alpha = 0.22) + 
  facet_wrap(vars(split)) +
  xlab("predicted") + 
  theme_minimal()
```

## Example of Lugano AR

```{r}
model_strat_fit %>% 
  filter(ARNAME == "Lugano") %>% 
  ggplot(aes(x = date)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`)) + 
  geom_point(aes(y = observed), col = "darkorchid", alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

## Aggregating all observed and pred over time

```{r}
model_strat_fit_agg <- model_strat_fit %>% 
  # mutate(population = ifelse(month == 1, population, NA)) %>% 
  group_by(date) %>% 
  summarise(observed = sum(observed),
            # population = sum(population),
            predicted = as.integer(sum(`0.5quant`)))

model_strat_fit_agg %>% 
  ggplot(aes(x = date)) + 
  geom_line(aes(y = predicted)) + 
  geom_line(aes(y = observed), col = "darkorchid", alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

## Region effect 

```{r}
model_strat_space <-
  ar21 %>%
  # tg3o_ar %>%
  left_join(data_strat %>% select(ARNR, id_space) %>% distinct()) %>%
  left_join(model_strat$summary.random$id_space %>%
              slice(1:nrow(ar21)) %>% 
              mutate(s1_l = exp(`0.025quant`),
                     s1_m = exp(`0.5quant`),
                     s1_u = exp(`0.975quant`)) %>% 
              select(ID, starts_with("s1")),
            by = c("id_space" = "ID")) # %>%
# left_join(model_strat$summary.random$id_space %>%
#             slice((nrow(ar21)+1):(2*nrow(ar21))) %>% 
#             mutate(ID = ID - nrow(ar21),
#                    s2_l = exp(`0.025quant`),
#                    s2_m = exp(`0.5quant`),
#                    s2_u = exp(`0.975quant`)) %>% 
#             select(ID, starts_with("s2")),
#           by = c("id_space" = "ID"))

tm_shape(model_strat_space) +
  tm_fill("s1_m")

# tm_shape(model_strat_space) +
#   tm_fill("s2_m")
```

## Performance 

```{r}
marg.variance <- inla.tmarginal(function(x) 1/x,
                                model_strat$marginals.hyperpar$"Precision for id_space")
inla.zmarginal(marg.variance)

rm(marg.variance)
```

```{r eval=FALSE, include=FALSE}
table(model_strat$cpo$failure > 0)
sum(-log(model_strat$cpo$cpo), na.rm = TRUE)
# model_strat$cpo$pit
```


<!-- ----------------------------------------------------- -->

# Adjusted modelling

```{r}
results_all <- read_rds("results/results_all.Rds")
```

## Model

```{r}
summary(results_all)
results_all$summary.hyperpar
```

## Month

```{r}
results_all_month <- results_all$summary.random$month %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

results_all_month %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()
```

## Year 

```{r}
results_all_year <- results_all$summary.random$id_year %>% 
  mutate(ID = ID + 2014, 
         `0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

results_all_year %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()
```

## Observed vs predicted

```{r}
results_all_fit <- bind_cols(
  data,
  results_all$summary.fitted.values
) %>% 
  mutate(split = ifelse(date <= as.Date("2019-12-01"), "Pre", "Pand"))

ggplot(results_all_fit) + 
  geom_point(aes(x = `0.5quant`, y = observed), alpha = 0.22) + 
  facet_wrap(vars(split)) +
  xlab("predicted") + 
  theme_minimal()
```

## Example of Lugano AR

```{r}
results_all_fit %>% 
  filter(ARNAME == "Lugano") %>% 
  filter(age == "80+" & sex == "Male") %>% 
  ggplot(aes(x = date)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`)) + 
  geom_point(aes(y = observed), col = "darkorchid", alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

## Aggregating all observed and pred over time

```{r}
results_all_fit_agg <- results_all_fit %>% 
  # mutate(population = ifelse(month == 1, population, NA)) %>% 
  group_by(date) %>% 
  summarise(observed = sum(observed),
            # population = sum(population),
            predicted = as.integer(sum(`0.5quant`)))

results_all_fit_agg %>% 
  ggplot(aes(x = date)) + 
  geom_line(aes(y = predicted)) + 
  geom_line(aes(y = observed), col = "darkorchid", alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

## Space effect 

```{r}
results_all_space <-
  ar21 %>%
  # tg3o_ar %>%
  left_join(data_strat %>% select(ARNR, id_space) %>% distinct()) %>%
  left_join(results_all$summary.random$id_space %>%
              slice(1:nrow(ar21)) %>% 
              mutate(s1_l = exp(`0.025quant`),
                     s1_m = exp(`0.5quant`),
                     s1_u = exp(`0.975quant`)) %>% 
              select(ID, starts_with("s1")),
            by = c("id_space" = "ID")) #%>%
# left_join(results_all$summary.random$id_space %>%
#             slice((nrow(ar21)+1):(2*nrow(ar21))) %>% 
#             mutate(ID = ID - nrow(ar21),
#                    s2_l = exp(`0.025quant`),
#                    s2_m = exp(`0.5quant`),
#                    s2_u = exp(`0.975quant`)) %>% 
#             select(ID, starts_with("s2")),
#           by = c("id_space" = "ID"))

tm_shape(results_all_space) +
  tm_fill("s1_m")

# tm_shape(results_all_space) +
#   tm_fill("s2_m")
```

## Performance 

```{r}
marg.variance <- inla.tmarginal(function(x) 1/x,
                                results_all$marginals.hyperpar$"Precision for id_space")
inla.zmarginal(marg.variance)

rm(marg.variance)
```

```{r eval=FALSE, include=FALSE}
table(results_all$cpo$failure > 0)
sum(-log(results_all$cpo$cpo), na.rm = TRUE)
# results_all$cpo$pit
```
