---
title: "2020 excess mortality & voting patterns in CH"
subtitle: "INLA models using GEM"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales,  
       sf, tmap,
       INLA)

import::from("sjmisc", "frq")
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)
```

<!-- ----------------------------------------------------- -->

# Setup 

## Data

```{r}
data <- read_rds("data/BfS-closed/monthly_deaths/w_deaths_2015_2020_year_fin.Rds") %>% 
  filter(age != "<40") %>% 
  # strata with double zeroes seem to be crashing
  filter(pop_mid_poi > 0) 

data_male <- data %>% 
  filter(sex == "Male") %>% 
  select(-sex) %>% 
  as.data.frame()

data_female <- data %>% 
  filter(sex == "Female") %>% 
  select(-sex) %>% 
  as.data.frame()
```

## Spatial 

```{r}
kt <- readRDS("data/BfS/kt.Rds")
gg <- readRDS("data/BfS/gg.Rds")
# tg3o <- readRDS("data/geo/tg3o.Rds")
```

<!-- ----------------------------------------------------- -->

# Model comparison

```{r}
gem_sex_iid <- read_rds("results/gem_sex_iid.Rds")
# gem_sex_bym <- read_rds("results/gem_sex_bym.Rds")
gem_sex_bym2 <- read_rds("results/gem_sex_bym2.Rds")
```

## DIC {.tabset}

### Males 

```{r}
dotchart(c(
  gem_sex_iid$Female$Poisson$dic$dic,
  # gem_sex_iid$Female$zeroinflatedpoisson0$dic$dic,
  gem_sex_iid$Female$zeroinflatedpoisson1$dic$dic,
  
  gem_sex_bym2$Female$Poisson$dic$dic,
  # gem_sex_bym2$Female$zeroinflatedpoisson0$dic$dic,
  gem_sex_bym2$Female$zeroinflatedpoisson1$dic$dic
),
labels = c("IID Poisson", 
           # "IID ZI Poison 0", 
           "IID ZI Poison 1",
           "BYM2 Poisson", 
           # "BYM ZI Poison 0", 
           "BYM2 ZI Poison 1"))
```

### Females 

```{r}
dotchart(c(
  gem_sex_iid$Male$Poisson$dic$dic,
  # gem_sex_iid$Male$zeroinflatedpoisson0$dic$dic,
  gem_sex_iid$Male$zeroinflatedpoisson1$dic$dic,
  
  gem_sex_bym2$Male$Poisson$dic$dic,
  # gem_sex_bym2$Male$zeroinflatedpoisson0$dic$dic,
  gem_sex_bym2$Male$zeroinflatedpoisson1$dic$dic
),
labels = c("IID Poisson", 
           # "IID ZI Poison 0", 
           "IID ZI Poison 1",
           "BYM2 Poisson", 
           # "BYM ZI Poison 0", 
           "BYM2 ZI Poison 1"))
```

## WAIC {.tabset}

### Males 

```{r}
dotchart(c(
  gem_sex_iid$Female$Poisson$waic$waic,
  # gem_sex_iid$Female$zeroinflatedpoisson0$waic$waic,
  gem_sex_iid$Female$zeroinflatedpoisson1$waic$waic,
  
  gem_sex_bym2$Female$Poisson$waic$waic,
  # gem_sex_bym2$Female$zeroinflatedpoisson0$waic$waic,
  gem_sex_bym2$Female$zeroinflatedpoisson1$waic$waic
),
labels = c("IID Poisson", 
           # "IID ZI Poison 0", 
           "IID ZI Poison 1",
           "BYM Poisson", 
           # "BYM ZI Poison 0", 
           "BYM ZI Poison 1"))
```

### Females 

```{r}
dotchart(c(
  gem_sex_iid$Male$Poisson$waic$waic,
  # gem_sex_iid$Male$zeroinflatedpoisson0$waic$waic,
  gem_sex_iid$Male$zeroinflatedpoisson1$waic$waic,
  
  gem_sex_bym2$Male$Poisson$waic$waic,
  # gem_sex_bym2$Male$zeroinflatedpoisson0$waic$waic,
  gem_sex_bym2$Male$zeroinflatedpoisson1$waic$waic
),
labels = c("IID Poisson", 
           # "IID ZI Poison 0", 
           "IID ZI Poison 1",
           "BYM Poisson", 
           # "BYM ZI Poison 0", 
           "BYM ZI Poison 1"))
```

<!-- ----------------------------------------------------- -->

# Best model

## Model 

```{r}
bym2_male <- gem_sex_bym2$Male
summary(bym2_male$Poisson)
bym2_male$Poisson$summary.hyperpar
```

## Year 

```{r}
bym2_male_year <- bym2_male$Poisson$summary.random$id_year %>% 
  mutate(ID = ID + 2014, 
         `0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

bym2_male_year %>% 
  ggplot(aes(y = ID)) + 
  geom_pointrange(aes(x = `0.5quant`, xmin = `0.025quant`, xmax = `0.975quant`)) + 
  theme_minimal() + 
  scale_x_log10()
```

## Age 

```{r}
bym2_male_age <- bym2_male$Poisson$summary.random$id_age %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

bym2_male_age %>% 
  ggplot(aes(y = ID)) + 
  geom_pointrange(aes(x = `0.5quant`, xmin = `0.025quant`, xmax = `0.975quant`)) + 
  theme_minimal() + 
  scale_x_log10()
```

## Observed vs predicted

```{r}
bym2_male_fit <- bind_cols(
  data_male,
  bym2_male$Poisson$summary.fitted.values
) %>% 
  remove_rownames() %>% 
  mutate(split = ifelse(year < 2020, "Pre-pandemic", "Pandemic"))

ggplot(bym2_male_fit) + 
  geom_point(aes(x = `0.5quant`, y = observed), alpha = 0.22) + 
  facet_wrap(vars(split)) +
  xlab("predicted") + 
  theme_minimal()
```

## Examples

### Lugano 

```{r}
bym2_male_fit %>% 
  filter(GMDNAME == "Lugano") %>% 
  ggplot(aes(x = year, fill = age, group = age)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`, color = age)) + 
  geom_point(aes(y = observed, color = age), alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

### Most error 2015-19

```{r}
bym2_male_fit %>% 
  filter(year < 2020) %>% 
  mutate(diff = as.integer(round(observed - `0.5quant`))) %>% 
  group_by(GMDNAME) %>% 
  summarize(diff = abs(sum(diff))) %>% 
  ungroup() %>% 
  arrange(desc(diff))

bym2_male_fit %>% 
  filter(GMDNAME == "Appenzell") %>% 
  ggplot(aes(x = year, fill = age, group = age)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`, color = age)) + 
  geom_point(aes(y = observed, color = age), alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()

bym2_male_fit %>% 
  filter(GMDNAME == "Rüte") %>% 
  ggplot(aes(x = year, fill = age, group = age)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`, color = age)) + 
  geom_point(aes(y = observed, color = age), alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()

bym2_male_fit %>% 
  filter(GMDNAME == "Goumoëns") %>% 
  ggplot(aes(x = year, fill = age, group = age)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`, color = age)) + 
  geom_point(aes(y = observed, color = age), alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

### Least error 2015-19

```{r}
bym2_male_fit %>% 
  filter(year < 2020) %>% 
  mutate(diff = as.integer(round(observed - `0.5quant`))) %>% 
  group_by(GMDNAME) %>% 
  summarize(diff = abs(sum(diff)),
            deaths = sum(deaths)) %>% 
  ungroup() %>% 
  arrange(diff) 

bym2_male_fit %>% 
  filter(GMDNAME == "Adlikon") %>% 
  ggplot(aes(x = year, fill = age, group = age)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`, color = age)) + 
  geom_point(aes(y = observed, color = age), alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()

bym2_male_fit %>% 
  filter(GMDNAME == "Horw") %>% 
  ggplot(aes(x = year, fill = age, group = age)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`, color = age)) + 
  geom_point(aes(y = observed, color = age), alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

## Aggregating all observed and pred over time

```{r}
bym2_male_fit_agg <- bym2_male_fit %>% 
  group_by(year) %>% 
  summarise(observed = sum(observed),
            # population = sum(population),
            predicted = as.integer(sum(`0.5quant`))) %>% 
  ungroup() %>% 
  mutate(diff = observed - predicted)

bym2_male_fit_agg

bym2_male_fit_agg %>% 
  ggplot(aes(x = year)) + 
  geom_line(aes(y = predicted)) + 
  geom_line(aes(y = observed), col = "darkorchid", alpha = 0.5) + 
  # facet_wrap(vars(split), scales = "free_x") +
  xlab("") + ylab("predicted/observed") +
  theme_minimal()
```

## Region effect 

```{r}
bym2_male_space <-
  gg %>%
  select(GMDNR) %>% 
  # tg3o %>%
  left_join(data_male %>% select(GMDNR, id_space) %>% distinct()) %>%
  left_join(bym2_male$Poisson$summary.random$id_space %>%
              mutate(s1_l = exp(`0.025quant`),
                     s1_m = exp(`0.5quant`),
                     s1_u = exp(`0.975quant`)) %>% 
              select(ID, starts_with("s1")),
            by = c("id_space" = "ID")) # %>%
```

```{r}
tm_shape(bym2_male_space) +
  tm_fill("s1_m", palette = "-BrBG", midpoint = 1, 
          title = "Region effect")
```

```{r}
bym2_male_space <-
  gg %>%
  select(GMDNR) %>% 
  # tg3o %>%
  left_join(data_male %>% 
              filter(year == 2020) %>% 
              group_by(GMDNR, id_space) %>% 
              summarise(pop_mid_poi = sum(pop_mid_poi)) %>% 
              ungroup()) %>%
  left_join(bym2_male$Poisson$summary.random$id_space %>%
              mutate(s1_l = exp(`0.025quant`),
                     s1_m = exp(`0.5quant`),
                     s1_u = exp(`0.975quant`)) %>% 
              select(ID, starts_with("s1")),
            by = c("id_space" = "ID")) # %>%
```

```{r}
tm_shape(kt) +
  tm_borders() +  
  tm_shape(bym2_male_space) +
  tm_symbols(size = "pop_mid_poi", col = "s1_m",
             shape = 15,
             palette = "-BrBG", midpoint = 1, 
             title.size = "Population", 
             title.col = "Region effect") + 
  tm_legend(position = c("left", "top"))
```

## Performance 

```{r}
marg.variance <- inla.tmarginal(function(x) 1/x,
                                bym2_male$Poisson$marginals.hyperpar$"Precision for id_space")
inla.zmarginal(marg.variance)
```

```{r eval=FALSE, include=FALSE}
table(bym2_male$Poisson$cpo$failure > 0)
sum(-log(bym2_male$Poisson$cpo$cpo), na.rm = TRUE)
# bym2_male$cpo$pit
```


