---
title: "Local correlates of excess mortality in Switzerland in 2020"
author: "Radoslaw Panczak, Julien Riou, Garyfallos Konstantinoudis, Matthias Egger"
date: "`r Sys.Date()`"
output: word_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---


```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, skimr, scales,
       hrbrthemes, 
       sf, tmap)

import::from("sjmisc", "frq")
import::from("weights", "wtd.cor")
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)
```